on: [pull_request]

jobs:
  branch_protection:
    runs-on: ubuntu-latest
    name: branch_protection
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: branch_protection
        uses: ./
        id: branch_protection
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
