on: [push]

jobs:
  branch_protection:
    runs-on: ubuntu-latest
    name: branch_protection
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - name: branch_protection
        uses: ./ # Uses an action in the root directory
        id: branch_protection
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Use the output from the `hello` step